Repository equalizedigital/accessibility-checker, pull requests merged in 2022-12, with the labels that each got.

#85 Fix "acessibility" typo in readme
  README.txt
Labels: documentation

#80 add context stream filter to allow disabling ssl verify
  includes/validate.php
Labels: enhancement

#83 fix undefined variable error
  includes/rules/color_contrast_failure.php
Labels: bug
