Repository equalizedigital/accessibility-checker, pull requests merged in 2024-07, with the labels that each got.

#696 Enahcement: Image inputs with alt text shouldn't flag for missing_form_label
  includes/rules/missing_form_label.php
Labels: bug

#705 Minor cleanup of admin styles
  src/admin/sass/accessibility-checker-admin.scss
Labels: Priority: Low

#695 Fix: Don't flag .avif as missing trascript or video present
  includes/classes/class-edac-dom.php
  includes/helper-functions.php
  includes/rules/video_present.php
Labels: bug

#710 Inline some single use variables at function returns
  admin/class-helpers.php
  admin/class-issues-query.php
  includes/helper-functions.php
Labels: enhancement

#679 Add wp cli commands to get stats and delete stats
  composer.json
  includes/classes/WPCLI/BootstrapCLI.php
  includes/classes/WPCLI/Command/CLICommandInterface.php
  includes/classes/WPCLI/Command/DeleteStats.php
  includes/classes/WPCLI/Command/GetSiteStats.php
  includes/classes/WPCLI/Command/GetStats.php
  includes/classes/class-plugin.php
  phpcs.xml
  tests/phpunit/TestHelpers/DatabaseHelpers.php
  tests/phpunit/TestHelpers/Mocks/Mock_WP_CLI.php
  tests/phpunit/includes/classes/WPCLI/BootstrapCLITest.php
  tests/phpunit/includes/classes/WPCLI/Commands/DeleteStatsTest.php
  tests/phpunit/includes/classes/WPCLI/Commands/GetSiteStatsTest.php
  tests/phpunit/includes/classes/WPCLI/Commands/GetStatsTest.php
Labels: enhancement, feature

#712 PHP 8.4 deprecation notice fix for implicitly nullable Meta_Boxes
  admin/class-admin.php
Labels: enhancement

#717 Fixed: background size style placement
  src/admin/sass/accessibility-checker-admin.scss
Labels: bug
