Repository equalizedigital/accessibility-checker, pull requests merged in 2024-06, with the labels that each got.

#673 Updated view on page aria-label with issue ID
  admin/class-ajax.php
Labels: a11y

#671 Added max width to issue image/svg
  src/admin/sass/accessibility-checker-admin.scss
Labels: bug

#670 Add filter to allow frontend highlighter to be shown to other users
  admin/class-frontend-highlight.php
  includes/classes/class-enqueue-frontend.php
Labels: enhancement

#672 Summary panel a11y
  admin/class-ajax.php
  includes/helper-functions.php
  src/admin/sass/accessibility-checker-admin.scss
Labels: a11y
